### ISSUE TITLE
[BUG] TypeError: create_record() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by lucasvdh** [chaptergy/certbot-dns-njalla#1]
Hi @chaptergy I've come across an error while trying to use your njalla plugin for certbot to renew a certificate. 

I'm not very experienced with Python so I don't really know whats going on. I'm hoping you can find something in the debug log.

```
2021-08-19 19:17:18,065:INFO:certbot.auth_handler:dns-01 challenge for x.y
2021-08-19 19:17:18,070:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): njal.la
2021-08-19 19:17:18,266:DEBUG:urllib3.connectionpool:https://njal.la:443 "POST /api/1/ HTTP/1.1" 200 None
2021-08-19 19:17:18,270:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/dist-packages/certbot_dns_njalla/dns_njalla.py", line 62, in _perform
    self._remove_subdomains(domain), validation_name, validation
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common_lexicon.py", line 43, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'

2021-08-19 19:17:18,270:DEBUG:certbot.error_handler:Calling registered functions
2021-08-19 19:17:18,270:INFO:certbot.auth_handler:Cleaning up challenges
2021-08-19 19:17:18,274:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): njal.la
2021-08-19 19:17:18,413:DEBUG:urllib3.connectionpool:https://njal.la:443 "POST /api/1/ HTTP/1.1" 200 None
2021-08-19 19:17:18,416:ERROR:certbot.error_handler:Encountered exception during recovery:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/dist-packages/certbot_dns_njalla/dns_njalla.py", line 62, in _perform
    self._remove_subdomains(domain), validation_name, validation
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common_lexicon.py", line 43, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/dist-packages/certbot_dns_njalla/dns_njalla.py", line 67, in _cleanup
    self._remove_subdomains(domain), validation_name, validation
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common_lexicon.py", line 65, in del_txt_record
    self.provider.delete_record(type='TXT', name=record_name, content=record_content)
TypeError: delete_record() got an unexpected keyword argument 'type'
2021-08-19 19:17:18,417:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1250, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 389, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/dist-packages/certbot_dns_njalla/dns_njalla.py", line 62, in _perform
    self._remove_subdomains(domain), validation_name, validation
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common_lexicon.py", line 43, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'
2021-08-19 19:17:18,418:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by lucasvdh** [comment]
You can ignore this! It was resolved by upgrading certbot and pip. 

Awesome work on this plugin!

**Comment by chaptergy** [comment]
Just for future reference, here is the [certbot PR fixing this](https://github.com/certbot/certbot/pull/8819).

**Comment by TheGroundZero** [comment]
I still seem to get this error.
Installed `certbot-dns-njalla` via pip today.

```bash
pip3 show certbot-dns-njalla
Name: certbot-dns-njalla
Version: 1.0.0
Summary: Njalla DNS Authenticator plugin for Certbot
Home-page: UNKNOWN
Author: Chaptergy
Author-email: 26956711+chaptergy@users.noreply.github.com
License: Apache License 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: certbot, setuptools, acme, zope.interface, dns-lexicon, dnspython, requests, mock
Required-by:
```

```bash
certbot --version
certbot 0.31.0
```

**Comment by chaptergy** [comment]
@TheGroundZero your certbot version is fairly outdated. The [current certbot version](https://github.com/certbot/certbot/releases/) as of October 2021 is 1.19.0 and the mentioned fix was only added in 1.16.0. Your version is from February 2019, so over two and a half years ago and does not include the fix.

**Comment by TheGroundZero** [comment]
> @TheGroundZero your certbot version is fairly outdated. The [current certbot version](https://github.com/certbot/certbot/releases/) as of October 2021 is 1.19.0 and the mentioned fix was only added in 1.16.0. Your version is from February 2019, so over two and a half years ago and does not include the fix.

Weird, as this is a fairly new system with a fresh install and I did try to update it with pip and it didn't upgrade anything.
You can see that pip also holds v1.0.0 and not 1.19.0
I'll have a look at it later today.

**Comment by chaptergy** [comment]
I am referring to certbot itself, not the certbot njalla plugin, as this was an issue in certbot. If you have installed certbot via pip as well make sure you have no other version of certbot installed and the certbot command actually points to the certbot binary installed via pip. Most likely you have installed certbot via apt on a Debian based system, as the packages on the Debian main repo are usually "stable" a.k.a. very outdated. Please check the [certbot instructions](https://certbot.eff.org/) on how to install it, which should install the newest version.

**Comment by renatofrota** [comment]
@TheGroundZero 

This did the trick for me on Ubuntu 20.04

```
apt remove certbot
apt remove python3-certbot
apt autoremove # remove related packages now marked as unnecessary
apt install python3-pip
pip3 uninstall certbot
pip3 install certbot
pip3 install mock
pip3 install zope-component
pip3 install certbot-dns-njalla
```

Thank you for this awesome script @chaptergy !
