### ISSUE TITLE
Certbot 2.3.0 compatibility issue

### ISSUE THREAD

**Issue by grantwest** [chaptergy/certbot-dns-njalla#5]
Running certbot snap 2.3.0 from the stable channel. 
Running certbot-dns-njalla 1.0.0

Run `certbot --help` and get this error:
```
An unexpected error occurred:
TypeError: 'type' object is not iterable
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-oyjpvxlp/log or re-run Certbot with -v for more details.
```

Log file:
```
2023-02-20 02:21:02,513:DEBUG:urllib3.connectionpool:http://localhost:None "GET /v2/connections?snap=certbot&interface=content HTTP/1.1" 200 787
2023-02-20 02:21:02,784:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/2772/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/2772/lib/python3.8/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/2772/lib/python3.8/site-packages/certbot/_internal/main.py", line 1833, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/snap/certbot/2772/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 192, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/snap/certbot/2772/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 199, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
  File "/snap/certbot/2772/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 40, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/snap/certbot/2772/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in load
    return self.resolve()
  File "/snap/certbot/2772/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2474, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/certbot-dns-njalla/current/lib/python3.8/site-packages/certbot_dns_njalla/dns_njalla.py", line 18, in <module>
    class Authenticator(dns_common.DNSAuthenticator):
  File "/snap/certbot-dns-njalla/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1108, in __call__
    directlyProvides(ob, *self.interfaces)
  File "/snap/certbot-dns-njalla/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 918, in directlyProvides
    interfaces = _normalizeargs(interfaces)
  File "/snap/certbot-dns-njalla/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1307, in _normalizeargs
    _normalizeargs(v, output)
  File "/snap/certbot-dns-njalla/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1306, in _normalizeargs
    for v in sequence:
TypeError: 'type' object is not iterable
2023-02-20 02:21:02,784:ERROR:certbot._internal.log:An unexpected error occurred:
2023-02-20 02:21:02,785:ERROR:certbot._internal.log:TypeError: 'type' object is not iterable
```

**Comment by chaptergy** [comment]
Weirdly enough, this problem does not occur with the local snap build. 

I'm not sure the fix you proposed would work, as a lot of descriptions of the official certbot plugins have a string as the description, not a tuple. And those who do have a tuple, have had it for years, so it would not have anything to do with v2.3.0.

I'm having the snap rebuilt, maybe that already fixes it.

**Comment by chaptergy** [comment]
It seems this has fixed the issue. If it's still there for you, let me know.
